name: Pac-Man eating commits

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pac-Man Contribution Graph
        uses: AndreRuperto/svg-pacman-contributions@main
        with:
          github_user_name: isrique9
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: github-dark
          output_directory: dist
